name: mobile_frontend_flutter
description: "Bhakti Calendar - Spiritual calendar with mock data for demo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock/
